#! /bin/sh

set -e

case "$1" in 
    remove|purge)
        dictdconfig -w
        invoke-rc.d dictd restart
        exit 0
     ;;


    upgrade|abort-upgrade|abort-remove|abort-deconfigure|in-favour|removing)
        exit 0;
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2;
        exit 0;
    ;;
esac
