#! /bin/sh

set -e

PACKAGE=dict-gcide

case "$1" in 
    configure)
        dictdconfig -w
        invoke-rc.d dictd restart
        exit 0
    ;;

    failed-upgrade|abort-upgrade|abort-remove|abort-deconfigure|in-favour|removing)
        exit 0;
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2;
        exit 0;
    ;;
esac
